# Generated by Django 4.2 on 2025-06-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userId',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
