# Generated by Django 4.2 on 2025-06-09 14:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='passwordHash',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userId',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True),
        ),
    ]
