# Generated by Django 4.2 on 2025-06-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_passwordhash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='customuser',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profession',
            field=models.CharField(choices=[('student', 'Student'), ('researcher', 'Researcher'), ('professional', 'Professional')], default='student', max_length=20),
        ),
    ]
