# Generated by Django 4.2 on 2025-06-10 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_is_staff_customuser_dateofbirth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_verified',
            new_name='is_staff',
        ),
    ]
